name: Update Readme With FPMI Departures

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -v "gspread==6.1.2"
            pip install numpy pandas

        - name: Change README
          env: # Or as an environment variable
            client_id: ${{ secrets.CLIENT_ID }}
            client_email: ${{ secrets.CLIENT_EMAIL }}
            private_key: ${{ secrets.PRIVATE_KEY }}
            private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          run: |
            python3 parse_from_sheet.py $client_id $client_email $private_key $private_key_id

        - uses: stefanzweifel/git-auto-commit-action@v5